name: OneGuard
description: $description
version: '${version}'

main: com.kobosh.oneGuard.OneGuard
api-version: '1.21.10'
load: POSTWORLD

authors: [ koboshchan ]
website: kobosh.com

permissions:
  oneguard.reload:
    description: Allows reloading OneGuard config
    default: op

